<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdAppEventosTipoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('Simmons01.prod_app_eventosTipo_tb')->insert([
            [
                'eprtID' => 1,
                'eprt_descripcion' => 'Iniciar Labores',
                'eprt_tipo' => 'Gestión',
                'eprt_departamento' => 'Producción',
                'eprt_orden_presenta' => 1,
                'eprt_icon' => 'EVENTOS_TIPO_Images/IniciarLabores.png',
                'eprt_requiere_seccion' => true,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 4,
                'eprt_descripcion' => 'Traslado Sección',
                'eprt_tipo' => 'Gestión',
                'eprt_departamento' => 'Producción',
                'eprt_orden_presenta' => 2,
                'eprt_icon' => 'EVENTOS_TIPO_Images/TrasladoSeccion.png',
                'eprt_requiere_seccion' => true,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => true,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 13,
                'eprt_descripcion' => 'Capacitación',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 3,
                'eprt_icon' => 'EVENTOS_TIPO_Images/Capacitacion.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 15,
                'eprt_descripcion' => 'Para Programada',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'Producción',
                'eprt_orden_presenta' => 4,
                'eprt_icon' => 'EVENTOS_TIPO_Images/ParaProgramada2.png',
                'eprt_requiere_seccion' => true,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => true,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 19,
                'eprt_descripcion' => 'Vacaciones',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 5,
                'eprt_icon' => 'EVENTOS_TIPO_Images/vacaciones.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => false,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 8,
                'eprt_descripcion' => 'RRHH/Seguridad',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 6,
                'eprt_icon' => 'EVENTOS_TIPO_Images/RecursosHumanos.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 11,
                'eprt_descripcion' => 'Personal Limpieza/Varios',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 7,
                'eprt_icon' => 'EVENTOS_TIPO_Images/PersonalLimpieza.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 10,
                'eprt_descripcion' => 'Personal Prestado A Bodega/Ventas',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 8,
                'eprt_icon' => 'EVENTOS_TIPO_Images/bodega.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 7,
                'eprt_descripcion' => 'Pruebas De Desarrollo',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'Producción',
                'eprt_orden_presenta' => 9,
                'eprt_icon' => 'EVENTOS_TIPO_Images/InvestigacionDesarrollo.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 18,
                'eprt_descripcion' => 'Falta Injustificada',
                'eprt_tipo' => 'Para No Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 10,
                'eprt_icon' => 'EVENTOS_TIPO_Images/FaltaInjustificada.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 5,
                'eprt_descripcion' => 'Para No Programadas Producción',
                'eprt_tipo' => 'Para No Programada',
                'eprt_departamento' => 'Producción',
                'eprt_orden_presenta' => 11,
                'eprt_icon' => 'EVENTOS_TIPO_Images/ParadaNoProgramadaProduccion1.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => true,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 6,
                'eprt_descripcion' => 'Reparación',
                'eprt_tipo' => 'Para No Programada',
                'eprt_departamento' => 'Producción',
                'eprt_orden_presenta' => 12,
                'eprt_icon' => 'EVENTOS_TIPO_Images/reparacion.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 9,
                'eprt_descripcion' => 'Inventario Físico',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 13,
                'eprt_icon' => 'EVENTOS_TIPO_Images/InventarioFisico.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 12,
                'eprt_descripcion' => 'Mantenimiento',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'Producción',
                'eprt_orden_presenta' => 14,
                'eprt_icon' => 'EVENTOS_TIPO_Images/mantenimiento1.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 20,
                'eprt_descripcion' => 'Permiso Materno',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 15,
                'eprt_icon' => 'EVENTOS_TIPO_Images/PermisoMaterno.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 17,
                'eprt_descripcion' => 'Permiso Medico',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 16,
                'eprt_icon' => 'EVENTOS_TIPO_Images/PermisoMedico.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 16,
                'eprt_descripcion' => 'Permiso Personal',
                'eprt_tipo' => 'Para Programada',
                'eprt_departamento' => 'RRHH',
                'eprt_orden_presenta' => 17,
                'eprt_icon' => 'EVENTOS_TIPO_Images/PermisoPersonal.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 14,
                'eprt_descripcion' => 'Corte De Energía',
                'eprt_tipo' => 'Para No Programada',
                'eprt_departamento' => 'Producción',
                'eprt_orden_presenta' => 18,
                'eprt_icon' => 'EVENTOS_TIPO_Images/CorteEnergia.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => true,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -1,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 100,
                'eprt_descripcion' => 'Finalizar Labores',
                'eprt_tipo' => 'Gestión',
                'eprt_departamento' => 'App',
                'eprt_orden_presenta' => 19,
                'eprt_icon' => 'EVENTOS_TIPO_Images/FinalizarLabores.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => false,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => 0,
                'eprt_hora_inicio'=> '00:00:00',
            ],
            [
                'eprtID' => 101,
                'eprt_descripcion' => 'Descanso 1',
                'eprt_tipo' => 'Gestión',
                'eprt_departamento' => 'App',
                'eprt_orden_presenta' => 100,
                'eprt_icon' => 'EVENTOS_TIPO_Images/FinalizarLabores.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => false,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -30,
                'eprt_hora_inicio'=> '11:55:00',
            ],
            [
                'eprtID' => 102,
                'eprt_descripcion' => 'Descanso 2',
                'eprt_tipo' => 'Gestión',
                'eprt_departamento' => 'App',
                'eprt_orden_presenta' => 101,
                'eprt_icon' => 'EVENTOS_TIPO_Images/FinalizarLabores.png',
                'eprt_requiere_seccion' => false,
                'eprt_requiere_hora_inicio' => true,
                'eprt_requiere_referencia' => false,
                'eprt_requiere_referencia_obligatoria' => false,
                'eprt_duración_predefinida' => -15,
                'eprt_hora_inicio'=> '16:31:00',
            ],
        ]);
    }
}

