version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - app-network

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  node:
    image: node:18
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "3000:3000" # Exponer el puerto 3000
    command: bash -c "npm install && npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
